version: "3.9"

# connect to azurite
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    hostname: azurite
    restart: unless-stopped
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - "$HOME/Projects/database/azurite:/data"
