# docker compose file for camunda
version: "3.2"
services:
  camunda:
    image: camunda/camunda-bpm-platform:latest
    container_name: "camunda"
    ports:
      - 8080:8080
    volumes:
      - ~/projects/camunda/data/:/camunda/data/
      - ~/projects/camunda/log/:/camunda/log/
    networks:
      - camunda_go_net

networks:
  camunda_go_net:
    driver: bridge
