version: "3.1"

services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - $HOME/Projects/database/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${SQL_ROOT_PASSWORD}
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 4080:8080
