version: "3.9"

services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    restart: unless-stopped
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - "$HOME/Projects/database/redis:/bitnami/redis/data"

volumes:
  redis_data:
    driver: local
