version: "3.9"

services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - $HOME/Projects/database/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${ROOT_PASSWORD}
